# src/main/resources/application-dev.yml
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/TestHaeil
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_schema:
        # MariaDB는 스키마 개념이 다르므로 제거하거나 주석 처리
        # default_schema: project_haeil # PostgreSQL 스키마 이름은 MariaDB에선 사용되지 않을 수 있음
    hibernate:
      ddl-auto: update # 개발시에는 update, 필요시 create