# src/main/resources/application-dev.yml
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/TestHaeil?useUnicode=true&characterEncoding=utf8&authenticationPlugins=mysql_native_password
    username: root
#    password: 1234
    password: 5012
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_schema: testhaeil
    hibernate:
      ddl-auto: update # 개발시에는 update, 필요시 create

