# src/main/resources/application-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.nsanhcfdfwaujvumzdnl
    password: kosmo154*** # 실제 배포 시에는 환경 변수로 관리하는 것이 더 안전
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: project_haeil # Supabase PostgreSQL 스키마 이름
    hibernate:
      ddl-auto: none # 배포 환경에서는 ddl-auto를 'none'으로 설정하여 실수로 DB 스키마가 변경되는 것을 방지 (스키마 변경은 마이그레이션 도구로 관리)
