# src/main/resources/application-dev.yml
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/TestHaeil
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_schema: testhaeil
    hibernate:
      ddl-auto: update # 개발시에는 update, 필요시 create